#!/venv/bin/python
import random
class Maze:
    def __init__(self,r,c):
        self.R=r; self.C=c; 
        self.B=[[0 for i in range(0,r)] for j in range(c)]

    def rand(self, n):
        ret=[]
        for _ in range(n):
            t=(random.randint(0,self.R),random.randint(0,self.C)) 
            while (t in ret): t=(random.randint(0,self.R),random.randint(0,self.C))
            ret.append(t)
        #for i in ret: print(i)
        for i in ret: self.B[i[0]],self.B[i[1]]=(1,1)
    def pb(self): for i in range(self.R): print(self.B[i])
m=Maze(10,10)
m.rand(1)
m.pb()


